#!/usr/bin/env bash
# A script that displays Best School 10 times and Hi after the 9th iteration using while and if

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 9 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi

    ((counter++))
done
